#!/bin/bash
#set -x
source /functions.sh

if [[ -v ADGUARD_SEND_REPORTS ]]; then
  adguardvpn-cli config set-telemetry "$ADGUARD_SEND_REPORTS"
else
  adguardvpn-cli config set-telemetry
fi

adguardvpn-cli status

if [[ $(adguardvpn-cli status | head -n 1) == "You are not logged in" ]]; then
  adguardvpn-cli login
fi

if [[ $(adguardvpn-cli status | head -n 1) != "VPN is disconnected" ]]; then
  adguardvpn-cli disconnect
  sleep 5
  if [[ $(adguardvpn-cli status | head -n 1) != "VPN is disconnected" ]]; then
    echo "NOT DISCONNECTED AFTER DISCONNECT - THIS SHOULD NOT HAPPEN!!!"
    docker stop $(hostname)
  fi
fi

HOST_IP=$(get_ip)
write_var "HOST_IP" "$HOST_IP"

if [[ -v ADGUARD_LOCATION ]]; then
  adguardvpn-cli connect -y -l "$ADGUARD_LOCATION" &
else
  adguardvpn-cli connect -y -f &
fi

sleep 5

if [[ ! $(adguardvpn-cli status | head -n 1) =~ ^Connected\ to\ .* ]]; then
  echo "Unable to connect to VPN, restarting..."
  sleep 5
  docker restart $(hostname)
fi

VPN_IP=$(get_ip)
write_var "VPN_IP" "$VPN_IP"

if [[ -n ${var+x} && "$HOST_IP" == "$VPN_IP" ]]; then
  echo "HOST_IP == VPN_IP THIS SHOULD NOT HAPPEN!!!"
  docker stop $(hostname)
fi
