name: adguard-vpn
services:
    adguard-vpn:
        build: .
        ports:
            - 9091:9091
            - 51413:51413
        container_name: adguard-vpn
        privileged: true
        env_file:
            - .env
        volumes:
            - transmission_config:/config
            - /var/run/docker.sock:/var/run/docker.sock
            - type: bind
              source: '${DOWNLOADS_PATH}'
              target: '/downloads'
        image: adguard-vpn
        restart: unless-stopped
volumes:
    transmission_config:
