name: adguard-vpn
services:
    adguard-vpn:
        build: .
        ports:
            - 9091:9091
            - 51413:51413
        container_name: adguard-vpn
        privileged: true
        env_file:
            - .env
        volumes:
            - transmission_config:/config
            - ${DOWNLOADS_PATH}:/downloads
        image: adguard-vpn
volumes:
    transmission_config:
